const stocks = [
    // --- Indian Stocks (Static) ---
    {
        symbol: "INFY",
        companyName: "Infosys Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Technology",
        industry: "Information Technology Services",
        currency: "INR",
        isDynamic: false,
        initialPrice: 1555.45,
        open: 1560.00,
        high: 1572.30,
        low: 1548.00,
        previousClose: 1580.70,
        change: -25.25,
        changePercent: -1.60,
        volume: 2450000
    },
    {
        symbol: "ONGC",
        companyName: "Oil and Natural Gas Corporation",
        exchange: "NSE",
        country: "IN",
        sector: "Energy",
        industry: "Oil & Gas Exploration & Production",
        currency: "INR",
        isDynamic: false,
        initialPrice: 116.80,
        open: 117.00,
        high: 118.25,
        low: 116.10,
        previousClose: 116.90,
        change: -0.10,
        changePercent: -0.09,
        volume: 8500000
    },
    {
        symbol: "TCS",
        companyName: "Tata Consultancy Services Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Technology",
        industry: "Information Technology Services",
        currency: "INR",
        isDynamic: false,
        initialPrice: 3194.80,
        open: 3205.00,
        high: 3220.00,
        low: 3185.00,
        previousClose: 3202.80,
        change: -8.00,
        changePercent: -0.25,
        volume: 1200000
    },
    {
        symbol: "KPITTECH",
        companyName: "KPIT Technologies Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Technology",
        industry: "Software Services",
        currency: "INR",
        isDynamic: false,
        initialPrice: 266.45,
        open: 258.00,
        high: 270.00,
        low: 255.20,
        previousClose: 257.35,
        change: 9.10,
        changePercent: 3.54,
        volume: 450000
    },
    {
        symbol: "QUICKHEAL",
        companyName: "Quick Heal Technologies Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Technology",
        industry: "Software Security Solutions",
        currency: "INR",
        isDynamic: false,
        initialPrice: 308.55,
        open: 310.00,
        high: 312.45,
        low: 307.00,
        previousClose: 309.00,
        change: -0.45,
        changePercent: -0.15,
        volume: 150000
    },
    {
        symbol: "WIPRO",
        companyName: "Wipro Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Technology",
        industry: "Information Technology Services",
        currency: "INR",
        isDynamic: false,
        initialPrice: 577.75,
        open: 575.00,
        high: 581.40,
        low: 574.00,
        previousClose: 575.90,
        change: 1.85,
        changePercent: 0.32,
        volume: 3800000
    },
    {
        symbol: "M&M",
        companyName: "Mahindra & Mahindra Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Automotive",
        industry: "Automobiles & Auto Components",
        currency: "INR",
        isDynamic: false,
        initialPrice: 779.80,
        open: 782.00,
        high: 785.00,
        low: 776.00,
        previousClose: 779.90,
        change: -0.10,
        changePercent: -0.01,
        volume: 980000
    },
    {
        symbol: "RELIANCE",
        companyName: "Reliance Industries Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Conglomerate",
        industry: "Oil & Gas, Retail, Telecom",
        currency: "INR",
        isDynamic: false,
        initialPrice: 2112.40,
        open: 2090.00,
        high: 2125.00,
        low: 2085.00,
        previousClose: 2082.40,
        change: 30.00,
        changePercent: 1.44,
        volume: 6700000
    },
    {
        symbol: "HUL",
        companyName: "Hindustan Unilever Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Consumer Goods",
        industry: "Personal Care & Household Products",
        currency: "INR",
        isDynamic: false,
        initialPrice: 512.40,
        open: 508.00,
        high: 516.00,
        low: 506.00,
        previousClose: 507.10,
        change: 5.30,
        changePercent: 1.04,
        volume: 1800000
    },
    {
        symbol: "BHARTIARTL",
        companyName: "Bharti Airtel Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Telecommunication",
        industry: "Telecom Services",
        currency: "INR",
        isDynamic: false,
        initialPrice: 541.15,
        open: 535.00,
        high: 544.50,
        low: 534.00,
        previousClose: 538.05,
        change: 3.10,
        changePercent: 0.58,
        volume: 4500000
    },
    {
        symbol: "HDFCBANK",
        companyName: "HDFCBANK Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Financial Services",
        industry: "Banking & Financial Services",
        currency: "INR",
        isDynamic: false,
        initialPrice: 1522.35,
        open: 1500.00,
        high: 1530.00,
        low: 1495.00,
        previousClose: 1383.40,
        change: 138.95,
        changePercent: 10.04,
        volume: 12000000
    },
    {
        symbol: "ITC",
        companyName: "ITC Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Conglomerate",
        industry: "Tobacco, FMCG, Hotels",
        currency: "INR",
        isDynamic: false,
        initialPrice: 207.90,
        open: 206.00,
        high: 209.50,
        low: 205.80,
        previousClose: 202.00,
        change: 5.90,
        changePercent: 2.92,
        volume: 15000000
    },
    {
        symbol: "SBIN",
        companyName: "State Bank of India",
        exchange: "NSE",
        country: "IN",
        sector: "Financial Services",
        industry: "Banking & Financial Services",
        currency: "INR",
        isDynamic: false,
        initialPrice: 430.20,
        open: 431.50,
        high: 435.00,
        low: 428.00,
        previousClose: 324.35,
        change: 105.85,
        changePercent: 32.63,
        volume: 22000000
    },
    {
        symbol: "TATAPOWER",
        companyName: "Tata Power Company Limited",
        exchange: "NSE",
        country: "IN",
        sector: "Utilities",
        industry: "Electric Power Utilities",
        currency: "INR",
        isDynamic: false,
        initialPrice: 124.15,
        open: 125.00,
        high: 126.80,
        low: 123.50,
        previousClose: 104.20,
        change: 19.95,
        changePercent: 19.15,
        volume: 9800000
    },

    // --- US Stocks (Dynamic - ~30 Stocks) ---
    {
        symbol: "AAPL",
        companyName: "Apple Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Technology",
        industry: "Consumer Electronics",
        currency: "USD",
        isDynamic: true,
        initialPrice: 180.50
    },
    {
        symbol: "MSFT",
        companyName: "Microsoft Corporation",
        exchange: "NASDAQ",
        country: "US",
        sector: "Technology",
        industry: "Systems Software",
        currency: "USD",
        isDynamic: true,
        initialPrice: 420.30
    },
    {
        symbol: "AMZN",
        companyName: "Amazon.com, Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Consumer Discretionary",
        industry: "Internet Retail",
        currency: "USD",
        isDynamic: true,
        initialPrice: 175.40
    },
    {
        symbol: "NVDA",
        companyName: "NVIDIA Corporation",
        exchange: "NASDAQ",
        country: "US",
        sector: "Technology",
        industry: "Semiconductors",
        currency: "USD",
        isDynamic: true,
        initialPrice: 875.20
    },
    {
        symbol: "GOOGL",
        companyName: "Alphabet Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Technology",
        industry: "Interactive Media & Services",
        currency: "USD",
        isDynamic: true,
        initialPrice: 150.80
    },
    {
        symbol: "META",
        companyName: "Meta Platforms, Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Technology",
        industry: "Interactive Media & Services",
        currency: "USD",
        isDynamic: true,
        initialPrice: 495.60
    },
    {
        symbol: "TSLA",
        companyName: "Tesla, Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Consumer Discretionary",
        industry: "Automobiles",
        currency: "USD",
        isDynamic: true,
        initialPrice: 170.20
    },
    {
        symbol: "AVGO",
        companyName: "Broadcom Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Technology",
        industry: "Semiconductors",
        currency: "USD",
        isDynamic: true,
        initialPrice: 1350.00
    },
    {
        symbol: "JPM",
        companyName: "JPMorgan Chase & Co.",
        exchange: "NYSE",
        country: "US",
        sector: "Financial Services",
        industry: "Diversified Banks",
        currency: "USD",
        isDynamic: true,
        initialPrice: 195.40
    },
    {
        symbol: "V",
        companyName: "Visa Inc.",
        exchange: "NYSE",
        country: "US",
        sector: "Financial Services",
        industry: "Consumer Finance",
        currency: "USD",
        isDynamic: true,
        initialPrice: 275.60
    },
    {
        symbol: "UNH",
        companyName: "UnitedHealth Group Incorporated",
        exchange: "NYSE",
        country: "US",
        sector: "Healthcare",
        industry: "Managed Healthcare",
        currency: "USD",
        isDynamic: true,
        initialPrice: 480.50
    },
    {
        symbol: "WMT",
        companyName: "Walmart Inc.",
        exchange: "NYSE",
        country: "US",
        sector: "Consumer Staples",
        industry: "Hypermarkets & Super Centers",
        currency: "USD",
        isDynamic: true,
        initialPrice: 60.30
    },
    {
        symbol: "XOM",
        companyName: "Exxon Mobil Corporation",
        exchange: "NYSE",
        country: "US",
        sector: "Energy",
        industry: "Integrated Oil & Gas",
        currency: "USD",
        isDynamic: true,
        initialPrice: 118.90
    },
    {
        symbol: "MA",
        companyName: "Mastercard Incorporated",
        exchange: "NYSE",
        country: "US",
        sector: "Financial Services",
        industry: "Consumer Finance",
        currency: "USD",
        isDynamic: true,
        initialPrice: 460.80
    },
    {
        symbol: "ORCL",
        companyName: "Oracle Corporation",
        exchange: "NYSE",
        country: "US",
        sector: "Technology",
        industry: "Application Software",
        currency: "USD",
        isDynamic: true,
        initialPrice: 125.40
    },
    {
        symbol: "PG",
        companyName: "The Procter & Gamble Company",
        exchange: "NYSE",
        country: "US",
        sector: "Consumer Staples",
        industry: "Household & Personal Products",
        currency: "USD",
        isDynamic: true,
        initialPrice: 160.20
    },
    {
        symbol: "HD",
        companyName: "The Home Depot, Inc.",
        exchange: "NYSE",
        country: "US",
        sector: "Consumer Discretionary",
        industry: "Home Improvement Retail",
        currency: "USD",
        isDynamic: true,
        initialPrice: 350.50
    },
    {
        symbol: "NFLX",
        companyName: "Netflix, Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Consumer Discretionary",
        industry: "Movies & Entertainment",
        currency: "USD",
        isDynamic: true,
        initialPrice: 610.40
    },
    {
        symbol: "ADBE",
        companyName: "Adobe Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Technology",
        industry: "Application Software",
        currency: "USD",
        isDynamic: true,
        initialPrice: 485.50
    },
    {
        symbol: "COST",
        companyName: "Costco Wholesale Corporation",
        exchange: "NASDAQ",
        country: "US",
        sector: "Consumer Staples",
        industry: "Hypermarkets & Super Centers",
        currency: "USD",
        isDynamic: true,
        initialPrice: 720.80
    },
    {
        symbol: "AMD",
        companyName: "Advanced Micro Devices, Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Technology",
        industry: "Semiconductors",
        currency: "USD",
        isDynamic: true,
        initialPrice: 160.40
    },
    {
        symbol: "CVX",
        companyName: "Chevron Corporation",
        exchange: "NYSE",
        country: "US",
        sector: "Energy",
        industry: "Integrated Oil & Gas",
        currency: "USD",
        isDynamic: true,
        initialPrice: 155.60
    },
    {
        symbol: "MRK",
        companyName: "Merck & Co., Inc.",
        exchange: "NYSE",
        country: "US",
        sector: "Healthcare",
        industry: "Pharmaceuticals",
        currency: "USD",
        isDynamic: true,
        initialPrice: 125.20
    },
    {
        symbol: "KO",
        companyName: "The Coca-Cola Company",
        exchange: "NYSE",
        country: "US",
        sector: "Consumer Staples",
        industry: "Soft Drinks",
        currency: "USD",
        isDynamic: true,
        initialPrice: 60.10
    },
    {
        symbol: "PEP",
        companyName: "PepsiCo, Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Consumer Staples",
        industry: "Soft Drinks",
        currency: "USD",
        isDynamic: true,
        initialPrice: 168.40
    },
    {
        symbol: "DIS",
        companyName: "The Walt Disney Company",
        exchange: "NYSE",
        country: "US",
        sector: "Consumer Discretionary",
        industry: "Movies & Entertainment",
        currency: "USD",
        isDynamic: true,
        initialPrice: 110.50
    },
    {
        symbol: "CSCO",
        companyName: "Cisco Systems, Inc.",
        exchange: "NASDAQ",
        country: "US",
        sector: "Technology",
        industry: "Communications Equipment",
        currency: "USD",
        isDynamic: true,
        initialPrice: 48.30
    },
    {
        symbol: "INTC",
        companyName: "Intel Corporation",
        exchange: "NASDAQ",
        country: "US",
        sector: "Technology",
        industry: "Semiconductors",
        currency: "USD",
        isDynamic: true,
        initialPrice: 35.80
    },
    {
        symbol: "NKE",
        companyName: "NIKE, Inc.",
        exchange: "NYSE",
        country: "US",
        sector: "Consumer Discretionary",
        industry: "Footwear",
        currency: "USD",
        isDynamic: true,
        initialPrice: 95.20
    },
    {
        symbol: "CRM",
        companyName: "Salesforce, Inc.",
        exchange: "NYSE",
        country: "US",
        sector: "Technology",
        industry: "Application Software",
        currency: "USD",
        isDynamic: true,
        initialPrice: 280.40
    }
];

module.exports = {
    stocks
};